import{a as y,S as h,i as c}from"./assets/vendor-mdVVRe9K.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function o(t){if(t.ep)return;t.ep=!0;const n=s(t);fetch(t.href,n)}})();const p="https://pixabay.com/api/",b="46020556-902bd777cf965228c32d535d7";async function w(e,r=1,s=15){const o=new URLSearchParams({key:b,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:s});try{return(await y.get(`${p}?${o}`)).data}catch(t){throw console.error("Error fetching images:",t),t}}let i;function L(e){const r=document.querySelector(".gallery"),s=e.map(o=>`
    <a href="${o.largeImageURL}" class="gallery-link">
      <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy" class="img-gallery"/>
      <ul class="list-wrapper">
        <li class="text-content"><b>Likes:</b> ${o.likes}</li>
        <li class="text-content"><b>Views:</b> ${o.views}</li>
        <li class="text-content"><b>Comments:</b> ${o.comments}</li>
        <li class="text-content"><b>Downloads:</b> ${o.downloads}</li>
      </ul>
    </a>
  `).join("");r.insertAdjacentHTML("beforeend",s),i?i.refresh():i=new h(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom"})}function f(e){e.insertAdjacentHTML("afterbegin",'<span class="loader"></span>')}function S(){const e=document.querySelector(".loader");e&&e.remove()}function q(){const e=document.querySelector(".gallery");e.innerHTML=""}function d(e){const r=document.querySelector(".btn-load-more");r.style.display=e?"block":"none"}let a=1,u="";const g=document.querySelector(".gallery"),C=document.querySelector(".search-form"),v=document.querySelector('input[name="searchQuery"]'),E=document.querySelector(".btn-load-more");C.addEventListener("submit",M);E.addEventListener("click",P);async function M(e){if(e.preventDefault(),u=v.value.trim(),!u){c.error({title:"Error",message:"Please enter a search query.",position:"topRight",backgroundColor:"red",messageColor:"white",titleColor:"white"});return}a=1,q(),f(g),await m()}async function P(){a+=1,f(g),await m()}async function m(){try{const e=await w(u,a);L(e.hits),$(),e.totalHits<=a*15?(d(!1),c.info({title:"Info",position:"topRight",message:"We're sorry, but you've reached the end of search results.",backgroundColor:"green",messageColor:"white",titleColor:"white"})):d(!0)}catch(e){console.error("Error fetching images:",e),c.error({title:"Error",message:`Error: ${e.message}`,position:"topRight",backgroundColor:"red",messageColor:"white",titleColor:"white"})}finally{S()}}function $(){const e=document.querySelector(".gallery a");if(e){const{height:r}=e.getBoundingClientRect();window.scrollBy({top:r*2.6,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
